(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.intVideo = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4));

	// Layer 4
	this.instance = new lib.Symbol2();
	this.instance.setTransform(516.9,405.6);

	this.feedback_2 = new lib.Symbol7();
	this.feedback_2.setTransform(678,359);

	this.feedback_1 = new lib.Symbol7();
	this.feedback_1.setTransform(678,297);

	this.feedback_0 = new lib.Symbol7();
	this.feedback_0.setTransform(678,234);

	this.Quest_no = new lib.Symbol5();
	this.Quest_no.setTransform(85.5,458.8);

	this.instance_1 = new lib.Symbol2();
	this.instance_1.setTransform(533.4,235.1);

	this.mc_0 = new lib.Symbol4();
	this.mc_0.setTransform(538.4,235.3);

	this.instance_2 = new lib.Symbol2();
	this.instance_2.setTransform(516.9,295.1);

	this.mc_1 = new lib.Symbol4();
	this.mc_1.setTransform(538.4,295.3);

	this.instance_3 = new lib.Symbol2();
	this.instance_3.setTransform(516.9,355.6);

	this.mc_2 = new lib.Symbol4();
	this.mc_2.setTransform(538.9,355.8);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A80037").s().p("AL7CyIA4gVIAAANIg4AVgA2BCtIA4gVIAAAOIg4AVgEgiJACtIA4gVIAAAOIg4AVgAP3CnIA4gWIAAAOIg4AUgAL8CGIAMgBIgGgGIgCgJQAAgKAGgGQAHgGALAAQAKABAGADIgDAKQgGgDgHAAQgEAAgFADQgDAEAAAGQAAAIAHADIAYgDIAAAMIgvAFgEAmrAB2IAJgQIAQAHIASADQARAAAJgJQAJgJAAgOIAAgHIgXAAQgZAAgPgOQgOgOAAgbQAAgaASgRQASgQAeAAIAfAAIAABfIAyAAIAAhNIAUAAIAABNIAaAAQAMAAAGgHQAGgIAAgNIAAgxIAVAAIAAA7QAFAKAHAFQAHADALAAIAPAAIAAhfIAUAAIAABfIA8AAIAAihIAVAAIAAC0Ih0AAQgLAAgJgDQgIgDgKgLQgFAIgJAFQgJAEgMAAIhiAAIAAAGQAAAYgOANQgOAPgbAAIgCAAQgXAAgSgNgEAnNgALQgMALABASQAAATAIAJQAIAIARAAIAWAAIAAhNIgKAAQgVABgNALgAcNB2IAJgQIARAHIASADQAQAAAJgJQAKgJAAgOIAAgHIgYAAQgaAAgOgOQgOgOAAgbQAAgaASgRQASgQAeAAIAgAAIAAB4QAAAYgPANQgOAPgbAAIgCAAQgXAAgSgNgAcwgLQgNALAAASQABATAIAJQAIAIAQAAIAXAAIAAhNIgKAAQgWABgLALgEAj1ACDQgWAAgNgRQgNgQAAgcQgBgPADgPQADgQAFgLIATAAQgIAVAAAkQAAAUAIAKQAKAMAOAAIALAAQAWAAAJgKQAKgJgBgUIAAi0IAVAAIAACzQAAAdgPAOQgOAQgfAAgAadCDQgWAAgNgRQgNgQAAgcQAAgPACgPQADgQAEgLIAUAAQgHAVAAAkQAAAUAHAKQAKAMANAAIAMAAQAWAAAJgKQAKgJAAgUIAAi0IAUAAIAACzQABAdgQAOQgNAQggAAgAPyB8IAGgRIAJAEIAIABQAMAAAFgJQAHgJAAgOIAAh5IAUAAIAABfIAdAAIACABIABgBIAmAAIAAhfIAVAAIAABfICFAAQgJgIgGgkQgDgSgIgJQgGgIgNAAQgRABgSAJIgJgRQALgGAKgDIAXgDQAPAAAKAGQAJAFAGAKQAGALADARQAEAWADALQAFAMAGAFIAAASIjWAAIgBgBIgCABIgdAAIAAAGQgBAYgKANQgLAPgVAAQgLgBgNgGgAvZCDQgXgBgNgPQgNgPAAgbQAAgdAKgYIAUAAQgIAVAAAeQAAAUAIAKQAIALAPAAIAMAAQAVAAAKgKQAJgKAAgTIAAhyIAUAAIAABfIAbAAIABABIABgBIAeAAQgJgWAAgSQAAgUAIgRQAJgHAMgFQALgEAMAAQAPAAALAHQALAHAHALQAGANAAAOQAAASgHAOQgHANgNAIQgLAHgRAAIhEAAIgBgBIgBABIgbAAQAAAcgOAPQgPAPgeAAgAs2gSQgHADgGAFIgDAKIAAAJIACAWIAHAXIARAAQARABAIgMQAIgKABgVQAAgMgJgKQgIgKgMAAgA10CDQgWgBgNgPQgMgPAAgbQAAgdAJgYIAUAAQgIAVAAAeQAAAUAIAKQAIALAPAAIAMAAQAVAAAJgKQAKgKAAgTIAAhyIAVAAIAABfIAaAAIABABIABgBIAmAAIAAhfIAWAAIAABfIA9AAIAAhfIAWAAIAAByIiPAAIgBgBIgBABIgaAAQAAAcgPAPQgPAPgeAAgEgiAACDQgVAAgNgRQgNgQgBgcQAAgPADgPQACgQAFgLIAUAAQgIAVAAAkQAAAUAIAKQAJAMAOAAIAMAAQAVAAAKgKQAJgJAAgUIAAi0IAVAAIAAChIAaAAIABABIABgBIAtAAIAAhfIAWAAIAAByIhDAAIgBgBIgBABIgaAAQgBAcgOAPQgPAPgeAAgAkCBzIA4gVIAAANIg4AVgAtOBzIA4gVIAAANIg4AVgEggOABzIA4gVIAAANIg4AVgEgqgABzIA3gVIAAANIg3AVgEgtPABzIA4gVIAAANIg4AVgAJoB1QgFgEAAgHQABgHADgDQAEgEAGAAQAHABADADQAEAEgBAGQABAHgEAEQgDAEgHAAQgGAAgDgEgAHBB1QgDgEAAgHQAAgHADgDQAEgEAGAAQAHABAEADQADAEAAAGQgBAHgCAEQgFAEgGAAQgFAAgFgEgAk+B1QgFgEAAgHQABgHADgDQAEgEAGAAQAHABADADQAEAEgBAGQABAHgEAEQgDAEgHAAQgGAAgDgEgAloB1QgEgDAAgIQAAgIAEgCQAFgEAEAAQAHAAADAEQAEADAAAHQABAHgFAEQgDAEgHAAQgFgBgEgDgAyRB1QgDgEAAgHQAAgHADgDQADgEAHAAQAGABAEADQADAEABAGQgBAHgDAEQgEAEgGAAQgGAAgEgEgAzNB1QgEgEAAgHQAAgHAEgDQADgEAHAAQAGABAEADQADAEAAAGQABAHgEAEQgDAEgHAAQgHAAgDgEgAz2B1QgEgDAAgIQAAgIAEgCQAEgEAFAAQAGAAAEAEQAEADAAAHQAAAHgEAEQgEAEgGAAQgGgBgDgDgA7LB1QgEgEAAgHQABgHADgDQAEgEAFAAQAHABADADQAEAEAAAGQAAAHgEAEQgCAEgIAAQgGAAgDgEgEgq9AB1QgEgEAAgHQAAgHAEgDQADgEAHAAQAGABAEADQADAEAAAGQAAAHgDAEQgEAEgGAAQgHAAgDgEgEgrnAB1QgDgDAAgIQAAgIADgCQAFgEAFAAQAHAAADAEQAEADAAAHQAAAHgEAEQgEAEgGAAQgGgBgEgDgAXqBIQgEgDAAgGQAAgEAEgFQAEgDAFAAQAFgBAEAEQAEAFAAAEQAAAGgEADQgEAEgFAAIgBAAQgFAAgDgEgAE3A7QgQgOAAgbQABgaAQgRQASgQAeAAIAQAAIAAgPIAVAAIAABuIA0AAIAAhfIAWAAIAAByIhzAAIgCAAQgcAAgPgOgAFIgLQgMALAAARQAAASALAKQAKAJATAAIAUAAIAAhNIgOAAQgWAAgMAMgAp0A7QgPgOAAgbQAAgaARgRQASgQAeAAIAQAAIAAgPIAVAAIAABuIB8AAQgJgJgHgjQgDgRgHgKQgGgIgOAAQgRABgRAJIgJgRQAKgGALgDIAXgDQAOAAAKAGQAKAFAFAKQAHALACARQAHAlAKAMIARAAIAAABIAAgBIAnAAIAAhfIAWAAIAABfICEAAQgJgJgGgjQgEgRgGgKQgHgIgOAAQgQABgSAJIgIgRQAKgGALgDIAWgDQAPAAAJAGQAKAFAGAKQAGALADARQAGAlALAMIAuAAIAAhYIAUAAIAAAqQALgZARgNQARgOAVAAQAcABALAOQAOAPAAAeIAAAmIA8AAIAAihIAWAAIAAC0InhAAIAAAAIjLAAIgBAAQgcAAgQgOgAhkAjIAAATIBkAAIAAgmQAAgUgJgKQgJgLgUAAQglAAgZA8gApjgLQgMALAAARQAAASALAKQAKAJATAAIAVAAIAAhNIgPAAQgWAAgMAMgEgtmAA7QgPgOgBgbQABgaARgRQASgQAeAAIAQAAIAAgPIAVAAIAABuIA7AAIAAhfIAWAAIAABfIA9AAIAAihIAWAAIAAC0IjOAAIgBAAQgcAAgQgOgEgtUgALQgMALAAARQgBASALAKQALAJASAAIAVAAIAAhNIgPAAQgVAAgMAMgEAthABJIAAi0IAVAAIAAC0gEAluABJIAAi0IAVAAIAAC0gEAg3ABJIAAi0IAVAAIAAC0gAeKBJIAAgTIA2AAIgfiBIAWAAIAfCBIAGAAQAaAAAAgcIAAiFIAVAAIAACIQABAVgMALQgNAMgUAAgAVUBJIAAi0IAUAAIAAC0gAN+BJIAAi0IAUAAIAAC0gALQBJIAAgTIA2AAIgfiBIAWAAIAfCBIAHAAQAZAAAAgcIAAiFIAWAAIAACIQgBAVgMALQgLAMgVAAgAI5BJIgCgBQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAIg1AAIAAi0IAWAAIAAChIAfAAIABABIACgBIBmAAQgJgIgGgkQgDgSgIgJQgGgIgNAAQgRABgSAJIgJgRQALgGAKgDIAXgDQAPAAAKAGQAJAFAGAKQAGALADARQAEAWADALQAFAMAGAFIAAASgACZBJIAAi0IAWAAIAAC0gA4xBJIAAi0IAVAAIAAC0gA7qBJIgBgBIgBABIh/AAIAAgTIBQAAQgEgggOgWQgNgVgYgQIAIgTQAcAPARAcQARAaAGApIAaAAIABABIABgBIAfAAIAAhfIAVAAIAABfIA7AAIAAihIAVAAIAAC0gA+jBJIAAi0IAVAAIAAC0gEgk9ABJIAAi0IAVAAIAAC0gEgoAABJIgBgBQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIg0AAIAAi0IAVAAIAAChIAfAAIACABIABgBIAnAAIAAhfIAVAAIAABfIA9AAIAAihIAWAAIAAC0gAXqgNQgEgEAAgGQABgEADgFQAEgEAFAAQAGABAEADQADAFAAAEQABAHgEADQgFADgFABIgBAAQgEAAgEgEgAvVgtQgDgEAAgGQAAgIADgDQAFgEAFAAQAHAAADAEQAEAEAAAHQABAFgFAFQgCAEgIAAQgFAAgFgEgA1ugtQgEgEAAgGQAAgIAEgDQADgEAHAAQAGAAAEAEQADAEAAAHQAAAFgDAFQgEAEgGAAQgHAAgDgEgEAplgAwQgEgGAAgLIAAgQIAMAAIAAANIACALQADADAFAAQAKAAAAgLIAAgWIALAAIAAARQAAAGACACQADADAEAAQAHgBACgDQACgDAAgGIAAgSIAMAAIAAAUQABALgGAGQgEAGgLAAQgLAAgGgHQgFAMgOAAQgJAAgGgGgAGrhBIA4gWIAAAOIg4AUgAyohBIA4gWIAAAOIg4AUgA7ihBIA4gWIAAAOIg4AUgEgrogBBIA3gWIAAAOIg3AUgAzvg+QgIgHABgMQAAgLAHgHQAGgGANgBQALABAIAHQAHAHAAAKQAAAMgHAHQgIAHgLAAQgNAAgGgHgAzmhaQgEAEAAAFQAAAOAOAAQAFgBAEgDQADgCAAgIQAAgFgDgEQgEgDgFAAQgGAAgEADgAcehDQgFgGAAgLIAAgPIANAAIAAAMIACAKQACAEAFAAQALAAAAgLIAAgWIAKAAIAAARQAAAGACACQADADAEAAQAIAAABgDQACgEAAgGIAAgSIANAAIAAAUQAAALgFAGQgFAGgLAAQgKAAgGgHQgFAMgPAAQgIAAgGgGgEAnEgBJIAMgCQgJgFABgKQgBgKAHgGQAHgGALABQAJAAAHADIgEAKQgFgCgHAAQgFAAgEADQgDADAAAGIABAHIAGAEIAYgDIAAAMIgvAGgAJOhLIA4gVIAAANIg4AVgAnxhLIA3gVIAAANIg3AVgA/5hKIAMgCQgJgFAAgKQAAgKAGgGQAIgGAKAAQAKAAAGAEIgDALQgFgDgIAAQgEAAgFADQgDADAAAGIACAHIAGAEIAYgDIAAAMIgvAGgATghEQgDgDAAgIQAAgGADgEQAEgEAGAAQAHAAADAEQAEAEAAAGQABAIgFADQgCAEgIAAIgBAAQgFAAgEgEgASQhEQgDgDAAgIQAAgGADgEQAEgEAGAAQAHAAADAEQADAEABAGQAAAIgEADQgDAEgHAAIgBAAQgGAAgDgEgARnhEQgEgDAAgIQABgGADgFQAEgDAGAAQAGAAAEAEQADAEAAAGQABAIgEADQgDAEgHAAIgCAAQgEAAgEgEgEgnEgBEQgEgDAAgIQAAgGAEgEQADgEAGAAQAHAAAEAEQADAEAAAGQAAAIgDADQgEAEgHAAIgBAAQgFAAgDgEgEgntgBEQgFgDAAgIQABgGAEgFQAEgDAFAAQAHAAADAEQAEAEgBAGQABAIgEADQgDAEgHAAIgBAAQgFAAgDgEgA9ohOIA4gUIAAAMIg4AWgAhRhIQgFgGAAgLIAAgPIAMAAIAAANIACAKQADADAFAAQAKAAAAgLIAAgVIALAAIAAARQABAGACACQACACAEABQAIgBABgDQADgDAAgHIAAgSIAMAAIAAAVQAAAKgFAGQgFAHgKgBQgMABgFgIQgFANgOAAQgKgBgFgGgAF3hSQgEgDABgIQgBgGAEgFQADgDAHAAQAHAAADADQAEAFAAAGQgBAHgDAEQgEADgGAAIgBABQgFAAgEgEgAFOhSQgEgCAAgJQAAgHAEgEQADgDAHAAQAGAAADADQADAFABAGQAAAIgEADQgDAEgGgBIgCABQgEAAgEgEgAozhSQgEgDAAgIQAAgGAEgFQADgDAHAAQAGAAAEADQADAFAAAGQAAAHgDAEQgFADgFAAIgCABQgFAAgDgEgApdhSQgDgCAAgJQgBgHAEgEQAEgDAGAAQAGAAADADQAEAFAAAGQAAAIgEADQgDAEgGgBIgBABQgFAAgEgEgEgsmgBSQgDgDAAgIQAAgGADgFQAEgDAGAAQAHAAADADQAEAFAAAGQAAAHgEAEQgDADgHAAIgBABQgFAAgEgEgEgtOgBSQgFgCAAgJQAAgHAFgEQADgDAGAAQAGAAAEADQADAFAAAGQABAIgEADQgEAEgGgBIgBABQgFAAgDgEgAvfhcQgGgHgBgMQABgMAGgGQAIgHALAAQAMABAHAGQAIAHAAALQAAAMgIAHQgHAGgMAAQgLAAgIgGgAvVh4QgEADABAGQgBANANAAQAGAAADgDQAEgDABgHQgBgFgEgEQgDgEgGAAQgFAAgEAEgAeQhqIALgCQgIgFAAgKQAAgKAHgGQAGgFALAAQAJAAAHADIgDALQgGgDgGAAQgGAAgDADQgEADAAAHIACAGIAFAFIAYgEIAAAMIguAGgEApkgBsIAHgKQAIAGAJAAIALgCQgHgJAAgLQAAgJAGgGQAGgFAJAAQAKAAAFAFQAGAGAAAIQAAAJgHAIQgHAIgKAFQgKAFgMAAIgBAAQgNAAgKgIgEAqOgCMQgDACAAAFQABAHAFAIQAGgDADgFIADgIQAAgEgDgCQgBgCgFgBIAAAAQgDAAgDADgEAjNgBsIAHgKQAJAFAIAAIAMgBQgIgKABgLQgBgJAHgFQAFgGAJABQAKAAAGAFQAFAFAAAJQAAAJgGAIQgHAIgKAEQgLAGgMAAIgBAAQgMAAgLgIgEAj3gCNQgCADAAAEQAAAIAGAIIAJgIIACgJQABgDgDgDIgGgCgAZ1hsIAHgKQAJAFAIAAIAMgBQgIgKAAgLQAAgJAHgFQAFgGAKABQAJAAAFAFQAGAFAAAJQABAJgIAIQgGAIgLAEQgKAGgLAAIgCAAQgMAAgLgIgAagiNQgDADAAAEQAAAIAGAIIAJgIIACgJQABgDgDgDIgGgCgARphzIA3gVIAAANIg3AVgEgnygBtQgEgGAAgLIAAgQIAMAAIAAAOIACAKQADACAEAAQALABAAgLIAAgVIALAAIAAAQQAAAGACACQADADAEAAQAHgBACgDQACgCAAgIIAAgRIAMAAIAAAUQABALgFAGQgGAGgKAAQgLAAgGgHQgEAMgPAAQgJAAgGgGgATVhvQgIgHAAgMQABgLAHgIQAGgGANAAQALABAHAGQAIAHAAALQAAAMgIAHQgHAGgLAAQgNAAgGgGgATeiMQgEAEAAAGQAAAOAOgBQAFAAAEgDQADgDAAgHQAAgFgDgFQgEgDgFAAQgGAAgEADgAcYh/IA4gVIAAANIg4AVgAhXiEIA4gVIAAANIg4AWgEAm4gCFIA4gVIAAANIg4AVgAFRiHIA4gVIAAANIg4AUgApaiHIA5gVIAAANIg5AUgAfoiEQgGgHAAgMQAAgLAGgHQAIgHALAAQAMABAIAGQAHAIAAAKQAAAMgHAHQgIAHgMAAQgLAAgIgHgAfyigQgDAEgBAFQAAAOANAAQAGAAADgEQAFgCAAgIQAAgFgFgEQgDgEgGABQgFgBgEAEgAMviEQgIgHAAgMQABgLAHgHQAGgHANAAQALABAHAGQAIAIAAAKQAAAMgIAHQgHAHgLAAQgNAAgGgHgAM4igQgDAEAAAFQgBAOAOAAQAFAAAEgEQADgCAAgIQAAgFgDgEQgEgEgFABQgGgBgEAEgA6GiEQgIgHABgMQAAgLAHgHQAGgHANAAQALABAIAGQAHAIAAAKQAAAMgHAHQgIAHgLAAQgNAAgGgHgA59igQgDAEgBAFQAAAOAOAAQAFAAAEgEQADgCAAgIQAAgFgDgEQgEgEgFABQgGgBgEAEgAeCimIA4gVIAAANIg4AVgEgn3gCpIA4gVIAAANIg4AVg");
	this.shape.setTransform(421.1,85.2);

	this.feedback_3 = new lib.Symbol12();
	this.feedback_3.setTransform(466,364.5);

	this.wrong_sign = new lib.Symbol15();
	this.wrong_sign.setTransform(261.1,113.8);

	this.right_sign = new lib.Symbol11();
	this.right_sign.setTransform(612.5,116.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#D30302").ss(4).p("ACCCCQg2A2hMAAQhLAAg2g2Qg1g2AAhMQAAhLA1g2QA2g2BLAAQBMAAA2A2QA1A2AABLQAABMg1A2g");
	this.shape_1.setTransform(261.1,114.8);

	this.hit_area = new lib.Symbol8();
	this.hit_area.setTransform(371.5,361.1,1.653,1.653);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#0FB00D").ss(4).p("AC4AAQAABMg2A2Qg2A2hMAAQhLAAg2g2Qg2g2AAhMQAAhLA2g2QA2g2BLAAQBMAAA2A2QA2A2AABLg");
	this.shape_2.setTransform(610.9,114.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#A80037").s().p("AhTBTIgBgBIAAgQIABgBIAdAAIAAhZIAUAAIAAArQALgZARgNQAPgOAVAAQAcABAOAOQANAPAAAdIAAA5gAgiAtIAAAUIBjAAIAAgmQAAgWgKgJQgJgKgUAAQgjAAgZA7gAAOg5QgEgEAAgHQAAgHAEgEQAEgDAGAAQAGAAAEADQADAEAAAHQABAHgEADQgDAFgHAAIgCAAQgFAAgDgEg");
	this.shape_3.setTransform(726.6,115.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#A80037").s().p("AgaADIA2gSIAAAMIg2AUg");
	this.shape_4.setTransform(728.9,104.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#A80037").s().p("AguBYQgNgMABgWQAAgPAIgOQAJgMATgNQgRgPgMgUQgMgUgDgRQAOgMAQgIQARgHAQAAQANABAQAEQAPAFAMAIQAAAXgMAVQgLAWgVAPQAOAFAOAAIAdAAIABABIAAAQIgBABIgdAAIgWgDIgVgJQgRAKgHAKQgHAKAAALQAAAQAJAGQAJAIATAAIAhgEIADAQIgbAFIgSABQgXAAgOgMgAgqhCQACAOAKAPQALAQAOALQAQgMAJgPQAJgPACgTQgRgJgQAAQgUAAgUAOg");
	this.shape_5.setTransform(711.5,121.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#A80037").s().p("AgSASQgHgHAAgLQABgKAGgHQAHgHALAAQALABAHAGQAIAHAAAKQAAALgIAHQgHAHgLAAQgLAAgHgHgAgIgIQgEADAAAFQAAANAMAAQAFgBADgDQAEgDAAgGQAAgEgEgEQgDgEgFAAQgEAAgEAEg");
	this.shape_6.setTransform(710.3,106.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#A80037").s().p("Ag3A7IgBgBIAAgRIABgBIAlAAQgHgGgGgLQgEgMAAgLQAAgcAPgPQAQgPAYAAIATACIAOAFIgGASQgPgGgNAAQggAAAAAnQAAASAIALQAGALANAAIArAAIAAATg");
	this.shape_7.setTransform(688.8,117.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#A80037").s().p("AgbAEIA3gUIAAAOIg3ASg");
	this.shape_8.setTransform(689.8,107.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#A80037").s().p("AhQBaIAAgSIA2AAIgfiBIAWAAIAgCBIAdAAIAAiiIAWAAIAACiIAfAAIABABIAAAQQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(675.4,114.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#A80037").s().p("AgbADIA3gTIAAANIg3AUg");
	this.shape_10.setTransform(678.7,102.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#A80037").s().p("Ag8A4IgBgBIAAgQIABgBIAeAAQgJgXAAgQQABgVAHgRQAJgIAMgEQAKgFALABQAPAAAMAGQALAHAGAMQAHANAAAPQAAAQgHAOQgHAOgNAHQgMAIgQgBgAgBgiQgHADgHAEIgCALIAAALIABAUIAIAXIAPAAQAQABAIgMQAJgKAAgUQAAgOgJgKQgHgKgNAAg");
	this.shape_11.setTransform(658.3,117.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#A80037").s().p("AgaADIA1gSIAAAMIg1AUg");
	this.shape_12.setTransform(658.8,108.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#A80037").s().p("AgwBMQgQgOAAgbQABgcARgPQASgQAcAAIAQAAIAAgPIAUAAIAABvIAbAAIACABIAAAQQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIhCAAIgCABQgbAAgQgPgAgfAEQgMALAAAUQAAASALAJQAKAKATAAIATAAIAAhNIgPAAQgUAAgMAJgAAOhBQgDgDAAgIQAAgGADgEQAEgEAGAAQAHAAADAEQAEAEAAAGQgBAHgDAEQgEAEgGAAIgBAAQgFAAgEgEgAgZhBQgEgCAAgJQAAgHAEgEQAEgDAGAAQAGAAADAEQAEAEAAAGQAAAIgEADQgDAEgGAAIgBAAQgFAAgEgEg");
	this.shape_13.setTransform(646.3,114.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#A80037").s().p("AgaADIA2gTIAAANIg2AUg");
	this.shape_14.setTransform(646.8,102.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#A80037").s().p("AgIByIAAimIATAAIAACmgAgVhKIAKgCQgIgGAAgJQABgLAGgFQAHgGAJAAQAJAAAHAEIgEALQgFgDgHAAQgEAAgDADQgEADAAAGIADAHIAEAEIAXgDIAAALIgsAHg");
	this.shape_15.setTransform(578.6,112.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#A80037").s().p("AgaAEIA1gUIAAAOIg1ASg");
	this.shape_16.setTransform(578.3,97.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#A80037").s().p("Ag8A4IgBgBIAAgQIABgBIAeAAQgJgXAAgQQAAgVAJgRQAIgIAMgEQAKgFAMABQAOAAAMAGQALAHAGAMQAHANgBAPQABAQgIAOQgGAOgNAHQgMAIgRgBgAgBgiQgIADgGAEIgCALIgBALIACAUIAHAXIAPAAQARABAIgMQAJgKAAgUQAAgOgIgKQgJgKgLAAg");
	this.shape_17.setTransform(567.2,117.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#A80037").s().p("AgbADIA2gSIAAAMIg2AUg");
	this.shape_18.setTransform(567.8,108.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#A80037").s().p("AgaBaIAAi0IAWAAIAACiIAdAAIABABIAAAQQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_19.setTransform(558.3,114.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#A80037").s().p("Ag9BfIAAg/QAAgKAEgHQAEgHAGgEQAHgEAIAAIACAAQgJgVAAgSQABgWAIgQQAIgIAMgEQAKgFAMAAQAPABALAGQALAHAHAMQAGAMAAAQQAAASgHAOQgHAMgNAHQgMAHgQAAIgfAAQgRAAAAASIAAA7gAgOhBIgDAKIAAAMIACAVIAHAWIAPAAQAQAAAJgJQAIgLAAgVQAAgOgIgKQgIgKgMAAQgNAAgNAKg");
	this.shape_20.setTransform(545,121.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#A80037").s().p("AgaADIA1gSIAAAMIg1AUg");
	this.shape_21.setTransform(545.4,108.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#A80037").s().p("AgJBaIAAi0IATAAIAAC0g");
	this.shape_22.setTransform(525.7,114.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#A80037").s().p("AgYBaIgBgBIAAgQIABgBIAdAAIAAiiIAVAAIAAC0g");
	this.shape_23.setTransform(516.7,114.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#A80037").s().p("AgSASQgHgHAAgLQABgKAGgHQAHgHALAAQALABAHAGQAIAHAAAKQAAALgIAHQgHAHgLAAQgLAAgHgHgAgIgIQgEADAAAFQAAANAMAAQAFgBADgDQAEgDAAgGQAAgEgEgEQgDgEgFAAQgEAAgEAEg");
	this.shape_24.setTransform(518,101);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#A80037").s().p("AAWA7IgWgJQgUALgXAAIgcAAIgBgBIAAgQIABgBIAbAAQASAAALgFQgKgGgJgNQgJgNgHgNQgHgOgCgNQANgMAQgIQARgHAPAAQAPABAPAEQAQAFALAIQAAAZgLAUQgLAWgVAOQANAFAOAAIAdAAIABABIAAAQIgBABIgcAAIgDABQgJAAgKgDgAgkgcQAEARAJAMQALAQAMAKQASgMAJgPQAJgNABgUQgQgJgSAAQgTAAgUAOg");
	this.shape_25.setTransform(507.3,117.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#A80037").s().p("AgaAEIA2gTIAAANIg2ASg");
	this.shape_26.setTransform(506.1,127.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#A80037").s().p("AgKBNQgDgDAAgHQAAgHADgEQAEgEAGAAQAEABAEAEQADAEABAGQAAAHgEADQgDAEgFABQgHgBgDgEgAgoAhIgBgBIAAgQIABgBIAeAAIAAhgIAUAAIAABgIAfAAIABABIAAAQIgBABg");
	this.shape_27.setTransform(496.3,120.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#A80037").s().p("AgaADIA2gSIAAAMIg2AUg");
	this.shape_28.setTransform(495.7,109.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#A80037").s().p("AgZBaIAAi0IAUAAIAACiIAeAAIACABIAAAQQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_29.setTransform(489.3,114.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#A80037").s().p("AggBPIAHgQIAJAEIAIAAQAIAAAHgIQAFgJAAgPIAAh4IAVAAIAAB3QAAAZgLANQgLAOgTAAQgLAAgNgHg");
	this.shape_30.setTransform(478.6,120.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#A80037").s().p("AgaADIA2gTIAAANIg2AUg");
	this.shape_31.setTransform(480.4,108.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#A80037").s().p("AgoBGQgOgOAAgbQAAgRAHgOQAHgPANgJQANgIAOAAQAPAAAMAJQANAJAIAPQAHAOAAAQQAAAcgOAOQgOANgbAAIgCABQgYAAgOgPgAgYgDQgJALAAAVQAAAlAhAAQAiABAAgmQABgVgKgLQgJgNgQAAQgNABgLAMgAAHg6QgEgEAAgHQABgHADgEQAEgEAGAAQAGABAEADQADAEAAAHQABAHgEADQgDAEgHAAIgBABQgFAAgEgEgAggg6QgEgEAAgHQABgHADgEQAEgEAFAAQAHABADADQAEAEAAAHQAAAHgEAEQgDADgHAAIgBABQgEAAgEgEg");
	this.shape_32.setTransform(469.4,115.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#A80037").s().p("AgbAEIA2gTIAAANIg2ASg");
	this.shape_33.setTransform(469.2,127.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#A80037").s().p("AgJBaIAAi0IATAAIAAC0g");
	this.shape_34.setTransform(450.7,114.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#A80037").s().p("AgYBaIgBgBIAAgQIABgBIAdAAIAAiiIAVAAIAAC0g");
	this.shape_35.setTransform(441.6,114.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#A80037").s().p("AhkA7IgBgBIAAgRIABgBIAdAAIAAhYIAVAAIAAAsQALgbARgNQARgOATAAQAbABAOAOQAOAPAAAdIAAAnIAgAAIABABIAAARIgBABgAgyAVIAAATIBjAAIAAgmQAAgUgKgKQgKgLgTAAQgjAAgZA8g");
	this.shape_36.setTransform(429.2,117.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#A80037").s().p("AgfAlQgFgGAAgMIAAgPIAMAAIAAAOIACAKQADACAFAAQAKABAAgMIAAgTIAJAAIAAAPQAAAGACACQADADAEAAQAHAAACgEQACgCAAgIIAAgPIANAAIAAASQAAALgFAGQgFAGgLAAQgLAAgGgHQgCAMgPAAQgJAAgFgGgAglgVIA2gVIAAANIg2AVg");
	this.shape_37.setTransform(429.2,105.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#A80037").s().p("AhEA7IgCgBIAAgRIACgBIBkAAQgJgJgGghQgDgUgIgJQgGgIgLAAQgRAAgSAKIgJgRQALgHAKgCIAXgDQANAAAKAFQAJAGAGAKQAGAKADAUQAGAjALAMIAQAAIABABIAAARQAAAAAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_38.setTransform(412.1,117.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#A80037").s().p("AgaAEIA2gTIAAANIg2ASg");
	this.shape_39.setTransform(411,127.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#A80037").s().p("AAMBNQgDgDAAgHQAAgHADgEQAEgEAGAAQAGABAEAEQADAEABAGQAAAHgEADQgDAEgHABQgGgBgEgEgAgbBOQgEgEAAgHQABgIADgDQAFgEAFAAQAGAAAEAEQADADAAAIQAAAHgDADQgEAEgGABQgGgBgEgDgAguAhIgCgBIAAgQIACgBIAmAAIAAhgIATAAIAABgIAkAAIABABIAAAQIgBABg");
	this.shape_40.setTransform(400.9,120.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#A80037").s().p("AhFA7IAAgBIAAgRIAAgBIBlAAQgJgJgGghQgEgUgGgJQgHgIgMAAQgQAAgSAKIgIgRQAKgHALgCIAWgDQANAAAJAFQAKAGAGAKQAGAKADAUQAGAjALAMIAQAAIACABIAAARQAAAAgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_41.setTransform(389.1,117.6);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#A80037").s().p("AgbAEIA2gUIAAAOIg2ASg");
	this.shape_42.setTransform(387.1,108.1);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#A80037").s().p("AgwBMQgQgOAAgbQABgcARgPQASgQAcAAIAQAAIAAgPIAUAAIAABvIAbAAIACABIAAAQQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIhCAAIgCABQgbAAgQgPgAgfAEQgMALAAAUQAAASALAJQAKAKATAAIATAAIAAhNIgPAAQgUAAgMAJgAAOhBQgDgDAAgIQAAgGADgEQAEgEAGAAQAHAAADAEQAEAEAAAGQgBAHgDAEQgEAEgGAAIgBAAQgFAAgEgEgAgZhBQgEgCAAgJQAAgHAEgEQAEgDAGAAQAGAAADAEQAEAEAAAGQAAAIgEADQgDAEgGAAIgBAAQgFAAgEgEg");
	this.shape_43.setTransform(376.2,114.4);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#A80037").s().p("AgaAEIA2gTIAAANIg2ASg");
	this.shape_44.setTransform(376.4,127.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#A80037").s().p("AgwBKIAKgQIAQAHIASACQAOAAAJgIQAKgJAAgPIAAgGIgYAAQgXAAgPgOQgOgOAAgZQAAgcASgRQASgQAcAAIAgAAIAAB3QAAAZgPANQgOAOgZAAIgCAAQgWAAgTgMgAgNg3QgMALAAAUQAAATAIAHQAIAIAPAAIAWAAIAAhNIgKAAQgTABgMALg");
	this.shape_45.setTransform(353.6,120.6);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#A80037").s().p("AgaADIA1gSIAAAMIg1AUg");
	this.shape_46.setTransform(353.7,108.4);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#A80037").s().p("Ag3A7IgBgBIAAgRIABgBIAlAAQgHgGgGgLQgEgMAAgLQAAgcAPgPQAQgPAYAAIATACIAOAFIgGASQgPgGgNAAQggAAAAAnQAAASAIALQAGALANAAIArAAIAAATg");
	this.shape_47.setTransform(340.7,117.6);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#A80037").s().p("AgaAEIA2gUIAAAOIg2ASg");
	this.shape_48.setTransform(341.7,107.9);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#A80037").s().p("AhPBaIAAgSIA2AAIggiBIAXAAIAeCBIAfAAIAAiiIAVAAIAACiIAfAAIACABIAAAQQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_49.setTransform(327.3,114.4);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#A80037").s().p("AgbADIA2gTIAAANIg2AUg");
	this.shape_50.setTransform(330.6,102.1);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#A80037").s().p("Ag8A4IgBgBIAAgQIABgBIAeAAQgJgXAAgQQAAgVAJgRQAIgIAMgEQAKgFALABQAPAAAMAGQALAHAGAMQAHANAAAPQAAAQgIAOQgGAOgNAHQgMAIgQgBgAgBgiQgIADgGAEIgCALIAAALIABAUIAHAXIAQAAQAQABAIgMQAJgKAAgUQAAgOgIgKQgJgKgMAAg");
	this.shape_51.setTransform(310.2,117.8);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#A80037").s().p("AgbADIA2gSIAAAMIg2AUg");
	this.shape_52.setTransform(310.7,108.4);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#A80037").s().p("AgwBMQgQgOAAgbQABgcARgPQASgQAcAAIAQAAIAAgPIAUAAIAABvIAbAAIACABIAAAQQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIhCAAIgCABQgbAAgQgPgAgfAEQgMALAAAUQAAASALAJQAKAKATAAIATAAIAAhNIgPAAQgUAAgMAJgAAOhBQgDgDAAgIQAAgGADgEQAEgEAGAAQAHAAADAEQAEAEAAAGQgBAHgDAEQgEAEgGAAIgBAAQgFAAgEgEgAgZhBQgEgCAAgJQAAgHAEgEQAEgDAGAAQAGAAADAEQAEAEAAAGQAAAIgEADQgDAEgGAAIgBAAQgFAAgEgEg");
	this.shape_53.setTransform(298.2,114.4);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#A80037").s().p("AgaADIA2gTIAAANIg2AUg");
	this.shape_54.setTransform(298.7,102.1);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#A80037").s().p("AgIByIAAimIATAAIAACmgAgWhKIALgCQgIgGAAgJQAAgLAHgFQAHgGAIAAQAKAAAHAEIgEALQgFgDgHAAQgEAAgDADQgEADABAGIACAHIAEAEIAWgDIAAALIgsAHg");
	this.shape_55.setTransform(230.5,112.1);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#A80037").s().p("AgbAEIA2gUIAAAOIg2ASg");
	this.shape_56.setTransform(230.2,97.9);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#A80037").s().p("Ag7A4IgBgBIAAgQIABgBIAdAAQgJgXAAgQQAAgVAJgRQAIgIAMgEQAKgFAMABQAOAAAMAGQALAHAHAMQAFANAAAPQAAAQgGAOQgHAOgNAHQgMAIgRgBgAgCgiQgGADgGAEIgDALIgBALIADAUIAGAXIAPAAQARABAIgMQAJgKAAgUQAAgOgIgKQgJgKgLAAg");
	this.shape_57.setTransform(219.1,117.8);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#A80037").s().p("AgbADIA2gSIAAAMIg2AUg");
	this.shape_58.setTransform(219.7,108.4);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#A80037").s().p("AgZBaIAAi0IAVAAIAACiIAdAAIACABIAAAQQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_59.setTransform(210.2,114.4);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#A80037").s().p("Ag9BfIAAg/QAAgKAEgHQAEgHAGgEQAHgEAIAAIACAAQgJgVAAgSQABgWAIgQQAIgIAMgEQAKgFAMAAQAPABALAGQALAHAHAMQAGAMAAAQQAAASgHAOQgHAMgNAHQgMAHgQAAIgfAAQgRAAAAASIAAA7gAgOhBIgDAKIAAAMIACAVIAHAWIAPAAQAQAAAJgJQAIgLAAgVQAAgOgIgKQgIgKgMAAQgNAAgNAKg");
	this.shape_60.setTransform(196.9,121.6);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#A80037").s().p("AgbADIA2gSIAAAMIg2AUg");
	this.shape_61.setTransform(197.3,108.4);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#A80037").s().p("AgJBaIAAi0IATAAIAAC0g");
	this.shape_62.setTransform(177.6,114.4);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#A80037").s().p("AgYBaIgBgBIAAgQIABgBIAdAAIAAiiIAVAAIAAC0g");
	this.shape_63.setTransform(168.6,114.4);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#A80037").s().p("AgSASQgHgHAAgLQABgKAGgHQAHgHALAAQALABAHAGQAIAHAAAKQAAALgIAHQgHAHgLAAQgLAAgHgHgAgIgIQgEADAAAFQAAANAMAAQAFgBADgDQAEgDAAgGQAAgEgEgEQgDgEgFAAQgEAAgEAEg");
	this.shape_64.setTransform(169.9,101);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#A80037").s().p("AAWA7IgWgJQgUALgXAAIgcAAIgBgBIAAgQIABgBIAbAAQASAAALgFQgKgGgJgNQgJgNgHgNQgHgOgCgNQANgMAQgIQARgHAPAAQAPABAPAEQAQAFALAIQAAAZgLAUQgLAWgVAOQANAFAOAAIAdAAIABABIAAAQIgBABIgcAAIgDABQgJAAgKgDgAgkgcQAEARAJAMQALAQAMAKQASgMAJgPQAJgNABgUQgQgJgSAAQgTAAgUAOg");
	this.shape_65.setTransform(159.2,117.3);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#A80037").s().p("AgaAEIA1gTIAAANIg1ASg");
	this.shape_66.setTransform(158,127.3);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#A80037").s().p("AgKBNQgEgDAAgHQABgHADgEQAEgEAGAAQAEABAEAEQADAEAAAGQABAHgEADQgDAEgFABQgGgBgEgEgAgoAhIgBgBIAAgQIABgBIAeAAIAAhgIAUAAIAABgIAfAAIABABIAAAQIgBABg");
	this.shape_67.setTransform(148.2,120.1);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#A80037").s().p("AgaADIA1gSIAAAMIg1AUg");
	this.shape_68.setTransform(147.6,109.1);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#A80037").s().p("AgZBaIAAi0IAUAAIAACiIAeAAIACABIAAAQQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_69.setTransform(141.2,114.4);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#A80037").s().p("AggBPIAHgQIAIAEIAJAAQAIAAAHgIQAFgJAAgPIAAh4IAVAAIAAB3QAAAZgLANQgLAOgTAAQgKAAgOgHg");
	this.shape_70.setTransform(130.5,120.6);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#A80037").s().p("AgaADIA1gTIAAANIg1AUg");
	this.shape_71.setTransform(132.3,108.8);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#A80037").s().p("AgoBGQgOgOAAgbQAAgRAHgOQAHgPANgJQANgIAOAAQAPAAAMAJQAOAJAHAPQAIAOgBAQQAAAcgOAOQgOANgbAAIgCABQgYAAgOgPgAgYgDQgJALAAAVQAAAlAhAAQAiABAAgmQABgVgKgLQgKgNgPAAQgNABgLAMgAAHg6QgEgEABgHQAAgHADgEQAEgEAGAAQAHABADADQAEAEAAAHQAAAHgEADQgDAEgHAAIgBABQgFAAgEgEgAggg6QgEgEAAgHQABgHADgEQAEgEAGAAQAGABAEADQADAEAAAHQAAAHgDAEQgFADgFAAIgCABQgEAAgEgEg");
	this.shape_72.setTransform(121.3,115.2);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#A80037").s().p("AgbAEIA2gTIAAANIg2ASg");
	this.shape_73.setTransform(121.2,127.3);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#A80037").s().p("AgJBaIAAi0IATAAIAAC0g");
	this.shape_74.setTransform(102.6,114.4);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#A80037").s().p("AgYBaIgBgBIAAgQIABgBIAdAAIAAiiIAVAAIAAC0g");
	this.shape_75.setTransform(93.6,114.4);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#A80037").s().p("AgSASQgHgHAAgLQABgKAGgHQAHgHALAAQALABAHAGQAIAHAAAKQAAALgIAHQgHAHgLAAQgLAAgHgHgAgIgIQgEADAAAFQAAANAMAAQAFgBADgDQAEgDAAgGQAAgEgEgEQgDgEgFAAQgEAAgEAEg");
	this.shape_76.setTransform(94.9,101);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#A80037").s().p("AhEBTIgCgBIAAgQIACgBIBkAAQgJgKgGgiQgDgUgIgHQgGgJgLAAQgRABgSAJIgJgQQALgHAKgDIAXgCQANAAAKAFQAJAGAGAKQAGAKADASQAGAlALAMIAQAAIABABIAAAQQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAgAgTg5QgDgEAAgHQAAgHADgEQAEgDAGAAQAHAAACADQADAEAAAHQABAHgEADQgBAFgIAAIgBAAQgFAAgEgEg");
	this.shape_77.setTransform(84,115.1);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#A80037").s().p("AgaADIA1gSIAAAMIg1AUg");
	this.shape_78.setTransform(82.7,104.1);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#A80037").s().p("AhkBaIgBgBIAAgQIABgBIAdAAIAAiiIAVAAIAAB0QALgaARgMQARgOATAAQAbABAOAOQAOANAAAfIAAAnIAgAAIABABIAAAQIgBABgAgyA0IAAAUIBjAAIAAgmQAAgWgKgLQgKgIgTAAQgjAAgZA7g");
	this.shape_79.setTransform(67.1,114.4);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#A80037").s().p("AgbAEIA2gTIAAAMIg2ATg");
	this.shape_80.setTransform(66.5,104.4);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#A80037").s().p("AgTByIAAimIATAAIAACUIAgAAIABABIAAAQQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAgAgghKIALgCQgJgGAAgJQABgLAGgFQAHgGALAAQAHAAAHAEIgEALQgFgDgFAAQgFAAgEADQgDADAAAGIACAHIAFAEIAWgDIAAALIgsAHg");
	this.shape_81.setTransform(53.5,112.1);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#A80037").s().p("ApDDCQgDgDAAgHQAAgGADgEQAEgFAGAAQAHABADAEQAEAEAAAGQAAAHgEADQgDAEgHABQgGgBgEgEgApsDDQgEgEAAgHQABgIADgDQAFgEAFAAQAGAAADAEQAEADAAAIQAAAHgDADQgEAEgGABQgGgBgEgDgAEGCKIAKgQIAQAHIASACQAQAAAJgIQAKgIAAgPIAAgHIgYAAQgZAAgPgOQgOgNAAgbQAAgdASgOQASgRAeAAIAgAAIAABgIAxAAIAAhNIAUAAIAABNIAaAAQAMAAAGgIQAGgHAAgNIAAgxIAVAAIAAA6QAFAKAIAEQAHAFALAAIAOAAIAAhgIAVAAIAABgIA7AAIAAiiIAWAAIAAC0Ih0AAQgLABgJgFQgJgCgKgLQgFAIgJAEQgJAFgMAAIhhAAIAAAFQAAAZgPAOQgOAOgbgBIgCABQgWAAgTgNgAEpAHQgMALAAAVQAAASAIAJQAIAJARAAIAWAAIAAhNIgKAAQgVAAgMAJgABQCWQgWAAgNgQQgNgQAAgdQAAgPADgPQACgOAFgMIAUAAQgIAVAAAjQAAAVAIALQAJALAOgBIAMAAQAVABAJgKQAKgJAAgTIAAi1IAUAAIAAC0QABAdgPAOQgOAPgfgBgApqCWQgWAAgNgPQgNgQAAgaIACgXIAHgUIATAAIgEAMIgCANIAAARQAAATAIAKQAIAKAPAAIAtAAQARABALgHQALgGAAgJQAAgEgEgEQgFgEgJgDQgSgEgHgEQgHgEgDgGQgEgFAAgIQABgOAIgNQAIgNANgIQAOgIAMAAQAJAAAGADIAMAJIAdAoIAIAJIAHAEIAJACIAdAAIAAhgIAVAAIAAByIg1AAQgIgBgJgEQgJgDgKgLIgMgQQgLgRgHgGQgHgGgGABQgHAAgHAEQgHAGgGAIQgFAHAAAGQABAEADADIAnAPIALAJQADAFAAAGQAAAwg9gBgAnBCHIA4gVIAAANIg4AVgArNBdQgEgEAAgFQAAgGAEgDQAEgFAFAAQAGAAADAFQAEADAAAGQAAAFgEAEQgDADgGAAIgBAAQgFAAgDgDgAK9BdIAAi0IAVAAIAAC0gADJBdIAAi0IAVAAIAAC0gAhrBdIAAi0IAVAAIAAC0gAkuBdIgBgBQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIg0AAIAAi0IAVAAIAACiIAfAAIACABIABgBIAmAAIAAhgIAWAAIAABgIA9AAIAAiiIAVAAIAAC0gArNAFQgEgEAAgDQABgFADgFQAEgDAFAAQAGAAAEADQADAFAAAFQABADgEAEQgEADgGAAIgBABQgEAAgEgEgAHBgcQgFgGAAgMIAAgOIAMAAIAAANIACAJQADADAFAAQAKABAAgMIAAgUIALAAIAAAQQAAAHACACQADACAEAAQAHgBACgCQACgEAAgHIAAgRIANAAIAAAUQAAALgFAGQgFAGgLAAQgLAAgGgHQgEAMgPAAQgJAAgFgGgAEgg1IALgCQgIgFAAgKQAAgKAGgGQAHgFALgBQAKABAGADIgEALQgEgDgIAAQgFAAgDADQgEADAAAGIACAHIAFAEIAYgCIAAALIguAGgAjygvQgEgFAAgGQAAgHAEgEQADgEAGAAQAHABADADQAEAEAAAHQAAAGgEAEQgDAEgHAAIgBAAQgGAAgCgDgAkcgvQgEgEAAgHQABgIADgDQAFgEAFAAQAHABADADQADAEAAAHQABAGgEAEQgDAEgHAAIgBAAQgFAAgEgDgAmkgvQgEgFAAgGQAAgHAEgEQADgEAHAAQAGABADADQAEAEAAAHQAAAGgEAEQgDAEgGAAIgCAAQgFAAgDgDgAkGhQQgEgCAAgIQAAgHAEgDQADgDAGAAQAFAAADADQAEAEAAAGQAAAIgEACQgEAEgEAAQgGAAgDgEgAG/hYIAHgKQAJAGAIAAIALgBQgHgLAAgKQAAgJAGgGQAGgFAJAAQAKABAFAEQAGAGAAAIQAAAJgHAIQgGAIgLAFQgKAFgMAAIgBAAQgMAAgLgIgAHph4QgCADAAAEQAAAHAGAIQAGgDADgEIACgJQABgDgDgDQgCgCgEAAIgBgBQgDAAgDADgAAohZIAHgKQAJAHAIAAIAMgCQgHgKAAgKQAAgJAGgGQAFgGAKAAQAKABAFAFQAFAGAAAHQABAKgHAHQgHAJgKAFQgKAEgMAAIgCABQgMAAgLgJgABTh4QgDACAAAFQAAAHAGAIIAJgIIADgIQAAgEgDgCIgGgDgAEThxIA4gVIAAANIg4AVgAkeh1QgFgFAAgMIAAgPIAMAAIAAANIACAKQADADAFAAQAKABAAgMIAAgVIALAAIAAARQAAAGACACQADADAEgBQAHAAACgDQACgDAAgHIAAgRIANAAIAAAUQAAAKgFAHQgFAFgLAAQgLAAgGgGQgEAMgPAAQgJAAgFgHgAkkiwIA4gWIAAAOIg4AUg");
	this.shape_82.setTransform(653.3,52.2);

	this.complete_question = new cjs.Text("", "bold 31px Arial", "#A80037");
	this.complete_question.lineHeight = 37;
	this.complete_question.lineWidth = 522;
	this.complete_question.setTransform(153.5,256);

	this.text = new cjs.Text("الثالث", "31px Adobe Fangsong Std R", "#A80037");
	this.text.lineHeight = 37;
	this.text.setTransform(591.5,42.9);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#A80037").s().p("AEGCCIAKgQIAQAHIASADQAQAAAJgJQAKgIAAgPIAAgHIgYAAQgZABgPgPQgOgNAAgbQAAgdASgOQASgRAeAAIAgAAIAABgIAxAAIAAhNIAUAAIAABNIAaAAQAMAAAGgIQAGgHAAgNIAAgxIAVAAIAAA6QAFAKAIAFQAHAEALAAIAOAAIAAhgIAVAAIAABgIA7AAIAAiiIAWAAIAAC0Ih0AAQgLABgJgEQgJgDgKgKQgFAHgJAFQgJAEgMAAIhhAAIAAAGQAAAYgPAOQgOAOgbAAIgCAAQgWAAgTgNgAEpAAQgMALAAAUQAAASAIAJQAIAJARAAIAWAAIAAhNIgKAAQgVAAgMAKgABQCPQgWAAgNgRQgNgQAAgcQAAgPADgPQACgPAFgMIAUAAQgIAVAAAkQAAAUAIALQAJALAOAAIAMAAQAVAAAJgKQAKgJAAgTIAAi1IAUAAIAAC0QABAdgPAOQgOAPgfAAgArNBVQgEgEAAgFQAAgFAEgEQAEgEAFAAQAGgBADAFQAEAEAAAFQAAAFgEAEQgDADgGAAIgBABQgFAAgDgEgAK9BVIAAi0IAVAAIAAC0gADJBVIAAi0IAVAAIAAC0gArNgBQgEgEAAgFQABgFADgEQAEgEAFAAQAGAAAEAEQADAEAAAFQABAGgEADQgEACgGAAIgBAAQgEAAgEgCgAHBgkQgFgGAAgLIAAgPIAMAAIAAANIACAKQADADAFAAQAKAAAAgLIAAgVIALAAIAAAQQAAAHACACQADACAEAAQAHAAACgDQACgDAAgHIAAgSIANAAIAAAUQAAALgFAGQgFAGgLAAQgLAAgGgHQgEAMgPAAQgJAAgFgGgAEgg9IALgCQgIgFAAgKQAAgKAGgGQAHgFALAAQAKAAAGADIgEALQgEgDgIAAQgFAAgDADQgEADAAAGIACAHIAFAFIAYgDIAAALIguAGgAG/hgIAHgKQAJAGAIAAIALgBQgHgKAAgLQAAgJAGgFQAGgGAJAAQAKABAFAFQAGAFAAAIQAAAJgHAIQgGAIgLAFQgKAFgMAAIgBABQgMAAgLgJgAHpiAQgCADAAAEQAAAIAGAHQAGgDADgEIACgJQABgDgDgDQgCgCgEAAIgBAAQgDAAgDACgAAohgIAHgKQAJAGAIAAIAMgCQgHgKAAgKQAAgJAGgGQAFgFAKAAQAKAAAFAFQAFAGAAAIQABAJgHAIQgHAIgKAFQgKAFgMAAIgCAAQgMAAgLgIgABTiAQgDACAAAFQAAAHAGAIIAJgIIADgIQAAgEgDgCIgGgDgAETh5IA4gVIAAANIg4AVg");
	this.shape_83.setTransform(653.3,52.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape},{t:this.mc_2},{t:this.instance_3},{t:this.mc_1},{t:this.instance_2},{t:this.mc_0},{t:this.instance_1},{t:this.Quest_no},{t:this.feedback_0},{t:this.feedback_1},{t:this.feedback_2},{t:this.instance}]},1).to({state:[{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.Quest_no},{t:this.shape_2},{t:this.hit_area},{t:this.shape_1},{t:this.right_sign},{t:this.wrong_sign},{t:this.feedback_3}]},1).to({state:[{t:this.shape_83},{t:this.Quest_no},{t:this.text},{t:this.complete_question}]},1).to({state:[]},1).wait(1));

	// Layer 6
	this.qu_mc = new lib.Symbol14();
	this.qu_mc.setTransform(379.1,162.6);
	this.qu_mc._off = true;

	this.timeline.addTween(cjs.Tween.get(this.qu_mc).wait(1).to({_off:false},0).to({_off:true},2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


// symbols:
(lib.Tween2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","#C20000"],[0,1],-192.9,-29.3,49.3,-29.3).s().p("AFJNTQmfkTl+o6IAEgFIAEAFIAAgJIAAtgQDADwC3C6QDGDNC8CMQBWA1AxA1QAwBDgXBHQg+EYAjDkQAnDUhVAAQgYAAgjgRg");
	this.shape.setTransform(47.4,44.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#000000","#C20000"],[0,1],194.7,-28.3,-50,-28.3).s().p("Am6KZQAkjkg+kXQgYhHAwhEQAyg1BXg1QC+iLDIjNQC5i7DCjwIAIgKIACgDIAFgGIAAATIAANeIgEAGIgEAFQmBI7mkESQgjASgYAAQhWAAAnjVg");
	this.shape_1.setTransform(-46.4,43.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#000000","#C20000"],[0,1],-192.4,50.2,49.8,50.2).s().p("AnRDqIAAgTIgFAGIgDgEQGCpFGlkWQCbhPgyESQgjDkA+EWQAXBHgwBDQgxA3hWA1QjBCPjMDVQi2i7jAjwg");
	this.shape_2.setTransform(48,-65.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#000000","#C20000"],[0,1],194.2,27.8,-50.5,27.8).s().p("AHeNwIAFgGIAAALIgFgFgAk4BRQhXg1gyg1QgwhEAXhHQA/kXgkjkQgykSCcBPQGqEWGGJGIADAEIgDACIgIAJQjCDxi4C6QjOjUjDiPg");
	this.shape_3.setTransform(-46.9,-43);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-95.2,-131.6,190.7,263.3);


(lib.Tween1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#009A00","#003000"],[0,1],-121,0,121.2,0).s().p("AkhQyIgYgcQltmwnYkVIgEgCQhDghBFgsIIEk5QBHgmAoA/IEPH+IABABIAAACIAHAKQAdArAVgoIAIgSQI8yhKYm1QCbhPgyESQgjDkA+EYQAXBHgwBDQgxA3hWA1QoAF5pXNgIgXAiQgmBSgrAAQgsAAgyhYg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-118.7,-116.2,237.6,232.6);


(lib.Symbol15 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D30302").s().p("AA5BxQgNgBgJgLIiEiOQgJgLgBgNQgBgNAJgIIAVgUQAJgIAMACQAOABAKALICDCOQAKALABANQAAANgIAJIgVATQgIAHgKAAIgFgBg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D30302").s().p("AhPBrIgUgTQgJgJAAgNQABgNAKgLICEiOQAJgLAOgBQAMgCAKAIIAUAUQAJAIgBANQgBANgJALIiECOQgJALgNABIgFABQgKAAgIgHg");

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.008)").s().p("AjfD6IAAnzIHAAAIAAHzg");
	this.shape_2.setTransform(0.8,-0.5);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-21.6,-25.6,45,50.1);


(lib.Symbol14 = function() {
	this.initialize();

	// Layer 1
	this.qu_txt = new cjs.Text(" ظَهَرَ الْإِسْلَامُ فِي  - ", "25px Arial", "#0081C5");
	this.qu_txt.textAlign = "right";
	this.qu_txt.lineHeight = 31;
	this.qu_txt.lineWidth = 551;
	this.qu_txt.setTransform(274.7,-13.6);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.008)").s().rr(-307.1,-38.5,614.2,77,25);

	this.addChild(this.shape,this.qu_txt);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-307,-38.4,614.2,77);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0FB00D").s().p("AAKA+IgQgQIgwgxQgFgFAAgJQAAgJAFgIIANgSQAFgHAJgCQAHgCAGAFIBJBDQAEAEgKAKIgSARIgNASQgDAFgFAAIgEgBg");
	this.shape.setTransform(-4.7,2.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0FB00D").s().p("Ag+BTIgRgPQgGgHAAgKQABgLAIgIIBohuQAHgJALgBQAKgBAHAHIARAPQAGAGAAALQgBAKgIAIIhoBvQgHAIgLACIgDAAQgJAAgFgGg");
	this.shape_1.setTransform(2.3,0);

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.008)").s().p("AjfD6IAAnzIHAAAIAAHzg");
	this.shape_2.setTransform(0.8,-0.5);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-21.6,-25.6,45,50.1);


(lib.Symbol8 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D2D2D2").s().p("AhBDsQg8gQgvgwQhHhHAAhlQAAhkBHhIQBIhHBkAAIAHAAQBgACBFBFQBJBIgBBkQABBlhJBHQhHBJhlgBQgiAAgfgIg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-24.4,-24.4,49,49);


(lib.Symbol5 = function() {
	this.initialize();

	// Layer 1
	this.total_question = new cjs.Text("", "bold 20px Arial", "#A80037");
	this.total_question.lineHeight = 25;
	this.total_question.setTransform(22,-16.2);

	this.current_question = new cjs.Text("", "bold 20px Arial", "#A80037");
	this.current_question.lineHeight = 25;
	this.current_question.setTransform(-33.9,-16.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A80037").s().p("AgiBYIA7ivIAKAAIg7Cvg");
	this.shape.setTransform(-1.4,-1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FD9A32").ss(1,1,1).p("AG1h7Qgmgmg2AAIqxAAQg2AAgmAmQgmAmAAA1IAABBQAAA1AmAmQAmAmA2AAIKxAAQA2AAAmgmQAmgmAAg1IAAhBQAAg1gmgmg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AlYCiQg2AAgmgmQglgmgBg1IAAhBQABg1AlgmQAmgmA2AAIKxAAQA2AAAmAmQAlAmABA1IAABBQgBA1glAmQgmAmg2AAg");

	this.addChild(this.shape_2,this.shape_1,this.shape,this.current_question,this.total_question);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-47.4,-16.2,95,32.5);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D2D2D2").s().p("AilCkQhEhEABhgQgBhfBEhFQBGhEBfgBQBgABBEBEQBFBFABBfQgBBghFBEQhEBFhgAAQhfAAhGhFg");
	this.shape.setTransform(85,0);

	this.ans_txt = new cjs.Text(" ظَهَرَ الْإِسْلَامُ فِي  - ", "25px Arial", "#3B3B3B");
	this.ans_txt.textAlign = "right";
	this.ans_txt.lineHeight = 31;
	this.ans_txt.setTransform(45.2,-12.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3399CC").s().p("AilCkQhEhEABhgQgBhfBEhFQBGhEBfgBQBgABBEBEQBFBFABBfQgBBghFBEQhEBFhgAAQhfAAhGhFg");
	this.shape_1.setTransform(85,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.ans_txt},{t:this.shape}]}).to({state:[{t:this.ans_txt},{t:this.shape_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125.7,-23.3,234.2,46.8);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(29).call(this.frame_29));

	// Layer 1
	this.instance = new lib.Tween1("synched",0);
	this.instance.setTransform(0,0,0.247,0.247);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.12,scaleY:0.12,alpha:1},29,cjs.Ease.get(-0.99)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-29.2,-28.6,58.6,57.4);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(29).call(this.frame_29));

	// Layer 1
	this.instance = new lib.Tween2("synched",0);
	this.instance.setTransform(0,0,0.194,0.194);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.09,scaleY:0.09,alpha:1},29,cjs.Ease.get(-0.99)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18.4,-25.5,37,51.1);


(lib.Symbol12 = function() {
	this.initialize();

	// wrong_fb
	this.wrong_fb = new lib.Symbol1();
	this.wrong_fb.setTransform(-1.6,-0.9);

	// right_fb
	this.right_fb = new lib.Symbol3();
	this.right_fb.setTransform(-2.9,0.4);

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.008)").s().p("Ak2EzQiBiAAAizQAAiyCBiAQCBh/C1AAQC2AACBB/QCACAABCyQgBCziACAQiBB/i2AAQi1AAiBh/g");

	this.addChild(this.shape,this.right_fb,this.wrong_fb);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-43.9,-43.4,88,87);


(lib.Symbol7 = function() {
	this.initialize();

	// wrong_fb
	this.wrong_fb = new lib.Symbol1();
	this.wrong_fb.setTransform(1.4,0);

	// right_fb
	this.right_fb = new lib.Symbol3();
	this.right_fb.setTransform(-0.9,-0.6);

	// BG
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(214,214,214,0.008)").s().p("AihCiQhEhDAAhfQAAheBEhDQBDhEBeAAQBfAABDBEQBEBDAABeQAABfhEBDQhDBEhfAAQheAAhDhEg");

	this.addChild(this.shape,this.right_fb,this.wrong_fb);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-30.2,-29.3,58.6,57.4);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol3();
	this.instance.setTransform(0,0,0.77,0.77);

	this.instance_1 = new lib.Symbol1();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},1).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;